Run actions/setup-node@v4
  with:
    node-version: 20
    cache: npm
    always-auth: false
    check-latest: false
    token: ***
Found in cache @ /opt/hostedtoolcache/node/20.19.5/x64
Environment details
  node: v20.19.5
  npm: 10.8.2
  yarn: 1.22.22
/opt/hostedtoolcache/node/20.19.5/x64/bin/npm config get cache
/home/runner/.npm
Error: Dependencies lock file is not found in /home/runner/work/Crocodile/Crocodile. Supported file patterns: package-lock.json,npm-shrinkwrap.json,yarn.lock
